src/OGIVE/AlertBundle/Entity/Additive.php
<?php

namespace OGIVE\AlertBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Additive
 *
 * @ORM\Table(name="additive")
 * @ORM\Entity(repositoryClass="\OGIVE\AlertBundle\Repository\AdditiveRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Additive extends AlertProcedure
{
    
   /**
     * @var \CallOffer
     *
     * @ORM\ManyToOne(targetEntity="CallOffer")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="callOffer", referencedColumnName="id")
     * })
     */
    private $callOffer;
    
    /**
     * @var \ExpressionInterest
     *
     * @ORM\ManyToOne(targetEntity="ExpressionInterest")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="expressionInterest", referencedColumnName="id")
     * })
     */
    private $expressionInterest;
    
    /**
     * Contructor
     */
    public function __construct() {
        parent::__construct();
        $this->setType("Additif");
    }
    
    /**
     * Set callOffer
     *
     * @param \OGIVE\AlertBundle\Entity\CallOffer $callOffer
     *
     * @return ProcedureResult
     */
    public function setCallOffer(\OGIVE\AlertBundle\Entity\CallOffer $callOffer=null) {
        $this->callOffer = $callOffer;

        return $this;
    }

    /**
     * Get callOffer
     *
     * @return \OGIVE\AlertBundle\Entity\CallOffer
     */
    public function getCallOffer() {
        return $this->callOffer;
    }
    
    /**
     * Set expressionInterest
     *
     * @param \OGIVE\AlertBundle\Entity\ExpressionInterest $expressionInterest
     *
     * @return ProcedureResult
     */
    public function setExpressionInterest(\OGIVE\AlertBundle\Entity\ExpressionInterest $expressionInterest=null) {
        $this->expressionInterest = $expressionInterest;

        return $this;
    }

    /**
     * Get expressionInterest
     *
     * @return \OGIVE\AlertBundle\Entity\ExpressionInterest
     */
    public function getExpressionInterest() {
        return $this->expressionInterest;
    }
    
    /**
     * @ORM\PrePersist() 
     */
    public function prePersist() {
        $this->createDate = new \DateTime();
        $this->lastUpdateDate = new \DateTime();
        $this->deadline = new \DateTime();
        $this->openingDate = new \DateTime();
        $this->sendingDate = new \DateTime('now');
        $this->status = 1;
    }
    
    public function getAbstractForSmsNotification() {
        $abstract = "";
        if ($this->getCallOffer()) {
            $abstract = "Ref : " . $this->getType() . " " . "N°" . explode("/", $this->getReference())[0] ." du " . $this->getStringDateForSms($this->getPublicationDate()) . " relatif a l'" . $this->getCallOffer()->getType() . " N°" .explode("/", $this->getCallOffer()->getReference())[0]." lance par " . $this->getCallOffer()->getOwner(). " le " . $this->getStringDateForSms($this->getCallOffer()->getPublicationDate()) . ".";
        } elseif ($this->getExpressionInterest()) {
            $abstract = "Ref : " . $this->getType() . " " . "N°" . explode("/", $this->getReference())[0] ." du " . $this->getStringDateForSms($this->getPublicationDate()). " relatif a l'" . $this->getExpressionInterest()->getType() . " N°" . explode("/", $this->getExpressionInterest()->getReference())[0]." lance par " . $this->getExpressionInterest()->getOwner() . " le " . $this->getStringDateForSms($this->getExpressionInterest()->getPublicationDate()). '.';
        } else {
            if (strlen(trim($this->getObject())) > 160) {
                $abstract = trim(substr($this->getObject(), 0, 157)) . "...";
            } else {
                $abstract = trim($this->getObject());
            }
        }
        return $abstract;
    }
    
    //get string date as dd/mm/yy
    public function getStringDateForSms($date){
        return date("d", strtotime($date))."/".date("m", strtotime($date))."/".substr(date("Y", strtotime($date)), -2);
    }
}

src/OGIVE/AlertBundle/Resources/views/send_sms/form_send_notification_additive.html.twig
<div id="send_notification_additive" class="ui small modal">
    <i class="close icon"></i>
    <div class="header">
        Notifier les abonnés de l'attribution N°{{additive.reference}}
    </div>
    <div class="content">
        <form method = 'POST' action= '{{path('send_notification_additive_post', {'id': additive.id})}}' class = 'ui form' id ='send_notification_additive_form' name='send_notification_additive_form'>
            <div class="field">
                <label>Le resumé à envoyer par SMS</label>
                <textarea id="abstract_sms" name='abstract_sms' rows="5">{{additive.abstractForSmsNotification}}</textarea>
                <label id="abstract_sms_length_notif">longueur du message : <span id="abstract_sms_count">{{additive.abstractForSmsNotification|length}}</span></label>
            </div>
            
            <div class="field">
                <label>Le resumé à envoyer par Email</label>
                <textarea name='abstract' rows="5">{{additive.abstract}}</textarea>
            </div>

            <div class="field" >
                <div class="ui checkbox">
                    <input id='checkbox_all_subscribers' type="checkbox" name="all_subscribers" >
                    <label> Notifier tous les abonnés du domaine</label>
                </div>
            </div>
            <div id='field_select_subscribers' class="field">
                <select id='subscribers'  name="subscribers" multiple="" class="ui search fluid dropdown">
                    <option value="">Selectionner les abonnés à notifier</option>
                    {%if subscribers%}
                        {%for subscriber in subscribers %}
                            <option value="{{subscriber.id}}">{{subscriber.name}}({{subscriber.entreprise.name}})</option>
                        {%endfor%} 
                    {%endif%}
                </select>
            </div>

            <div id='field_common_notification' class="field">
                <select id='notificationTypes'  name="common_notification" class="ui search fluid dropdown">
                    <option value="">Selectionner un type de notification commun si nécessaire</option>                    
                    <option value="3">SMS et Email</option>
                    <option value="2">SMS seulement</option>
                    <option value="1">Email seulement</option>
                </select>
            </div>

            <div class="field">
                <div id="server_error_message_send_notification" class="ui negative message" style="display:none">
                    <i class="close icon"></i>
                    <div id="server_error_content_send_notification" class="header">Internal server error</div>
                </div>
                <div id="error_name_message_send_notification" class="ui error message" style="display: none">
                    <i class="close icon"></i>
                    <div id="error_name_header_send_notification" class="header"></div>
                    <ul id="error_name_list_send_notification" class="list">

                    </ul>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <div id="cancel_send_notification_additive" class="ui black deny button">
            Annuler
        </div>
        <div id='submit_send_notification_additive' class="ui primary icon button">
            <i class="send icon"></i>
            Envoyer
        </div>
    </div>
</div>

src/OGIVE/AlertBundle/Resources/views/send_sms/form_send_notification_callOffer.html.twig
<div id="send_notification_callOffer" class="ui small modal">
    <i class="close icon"></i>
    <div class="header">
        Notifier les abonnés de l'{{callOffer.type}} N°{{callOffer.reference}}
    </div>
    <div class="content">
        <form method = 'POST' action= '{{path('send_notification_callOffer_post', {'id': callOffer.id})}}' class = 'ui form' id ='send_notification_callOffer_form' name='send_notification_callOffer_form'>
            <div class="field">
                <label>Le resumé à envoyer par SMS</label>
                <textarea id="abstract_sms" name='abstract_sms' rows="5">{{callOffer.abstractForSmsNotification}}</textarea>
                <label id="abstract_sms_length_notif">longueur du message : <span id="abstract_sms_count">{{callOffer.abstractForSmsNotification|length}}</span></label>
            </div>
            
            <div class="field">
                <label>Le resumé à envoyer par Email</label>
                <textarea name='abstract' rows="5">{{callOffer.abstract}}</textarea>
            </div>

            <div class="field" {% if callOffer.type == "AONR" or callOffer.type== "AOIR" %} style="display: none" {% endif %}>
                <div class="ui checkbox">
                    <input id='checkbox_all_subscribers' type="checkbox" name="all_subscribers">
                    <label> Notifier tous les abonnés du domaine</label>
                </div>
            </div>
            <div id='field_select_subscribers' class="field">
                <select id='subscribers'  name="subscribers" multiple="" class="ui search fluid dropdown">
                    <option value="">Selectionner les abonnés à notifier</option>
                    {%if subscribers%}
                        {%for subscriber in subscribers %}
                            <option value="{{subscriber.id}}">{{subscriber.name}}({{subscriber.entreprise.name}})</option>
                        {%endfor%} 
                    {%endif%}
                </select>
            </div>
            <div id='field_common_notification' class="field">
                <select id='notificationTypes'  name="common_notification" class="ui search fluid dropdown">
                    <option value="">Selectionner un type de notification commun si nécessaire</option>                    
                    <option value="3">SMS et Email</option>
                    <option value="2">SMS seulement</option>
                    <option value="1">Email seulement</option>
                </select>
            </div>

            <div class="field">
                <div id="server_error_message_send_notification" class="ui negative message" style="display:none">
                    <i class="close icon"></i>
                    <div id="server_error_content_send_notification" class="header">Internal server error</div>
                </div>
                <div id="error_name_message_send_notification" class="ui error message" style="display: none">
                    <i class="close icon"></i>
                    <div id="error_name_header_send_notification" class="header"></div>
                    <ul id="error_name_list_send_notification" class="list">

                    </ul>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <div id="cancel_send_notification_callOffer" class="ui black deny button">
            Annuler
        </div>
        <div id='submit_send_notification_callOffer' class="ui primary icon button">
            <i class="send icon"></i>
            Envoyer
        </div>
    </div>
</div>

src/OGIVE/AlertBundle/Resources/views/send_sms/form_send_notification_expressionInterest.html.twig
<div id="send_notification_expressionInterest" class="ui small modal">
    <i class="close icon"></i>
    <div class="header">
        Notifier les abonnés de l'ASMI N°{{expressionInterest.reference}}
    </div>
    <div class="content">
        <form method = 'POST' action= '{{path('send_notification_expressionInterest_post', {'id': expressionInterest.id})}}' class = 'ui form' id ='send_notification_expressionInterest_form' name='send_notification_expressionInterest_form'>
            <div class="field">
                <label>Le resumé à envoyer par SMS</label>
                <textarea id='abstract_sms' name='abstract_sms' rows="5">{{expressionInterest.abstractForSmsNotification}}</textarea>
                <label id="abstract_sms_length_notif">longueur du message : <span id="abstract_sms_count">{{expressionInterest.abstractForSmsNotification|length}}</span></label>
            </div>
            
            <div class="field">
                <label>Le resumé à envoyer par Email</label>
                <textarea name='abstract' rows="5">{{expressionInterest.abstract}}</textarea>
            </div>

            <div class="field" >
                <div class="ui checkbox">
                    <input id='checkbox_all_subscribers' type="checkbox" name="all_subscribers">
                    <label> Notifier tous les abonnés du domaine</label>
                </div>
            </div>
            <div id='field_select_subscribers' class="field">
                <select id='subscribers'  name="subscribers" multiple="" class="ui search fluid dropdown">
                    <option value="">Selectionner les abonnés à notifier</option>
                    {%if subscribers%}
                        {%for subscriber in subscribers %}
                            <option value="{{subscriber.id}}">{{subscriber.name}}({{subscriber.entreprise.name}})</option>
                        {%endfor%} 
                    {%endif%}
                </select>
            </div>
            <div id='field_common_notification' class="field">
                <select id='notificationTypes'  name="common_notification" class="ui search fluid dropdown">
                    <option value="">Selectionner un type de notification commun si nécessaire</option>                    
                    <option value="3">SMS et Email</option>
                    <option value="2">SMS seulement</option>
                    <option value="1">Email seulement</option>
                </select>
            </div>

            <div class="field">
                <div id="server_error_message_send_notification" class="ui negative message" style="display:none">
                    <i class="close icon"></i>
                    <div id="server_error_content_send_notification" class="header">Internal server error</div>
                </div>
                <div id="error_name_message_send_notification" class="ui error message" style="display: none">
                    <i class="close icon"></i>
                    <div id="error_name_header_send_notification" class="header"></div>
                    <ul id="error_name_list_send_notification" class="list">

                    </ul>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <div id="cancel_send_notification_expressionInterest" class="ui black deny button">
            Annuler
        </div>
        <div id='submit_send_notification_expressionInterest' class="ui primary icon button">
            <i class="send icon"></i>
            Envoyer
        </div>
    </div>
</div>

src/OGIVE/AlertBundle/Resources/views/send_sms/form_send_notification_procedureResult.html.twig
<div id="send_notification_procedureResult" class="ui small modal">
    <i class="close icon"></i>
    <div class="header">
        Notifier les abonnés de l'attribution N°{{procedureResult.reference}}
    </div>
    <div class="content">
        <form method = 'POST' action= '{{path('send_notification_procedureResult_post', {'id': procedureResult.id})}}' class = 'ui form' id ='send_notification_procedureResult_form' name='send_notification_procedureResult_form'>
            <div class="field">
                <label>Le resumé à envoyer par SMS</label>
                <textarea id='abstract_sms' name='abstract_sms' rows="5">{{procedureResult.abstractForSmsNotification}}</textarea>
                <label id="abstract_sms_length_notif">longueur du message : <span id="abstract_sms_count">{{procedureResult.abstractForSmsNotification|length}}</span></label>
            </div>
            
            <div class="field">
                <label>Le resumé à envoyer par Email</label>
                <textarea name='abstract' rows="5">{{procedureResult.abstract}}</textarea>
            </div>

            <div class="field" {%if procedureResult.callOffer %} {% if procedureResult.callOffer.type == "AONR" or procedureResult.callOffer.type== "AOIR" %} style="display: none" {% endif %}{% endif %}>
                <div class="ui checkbox">
                    <input id='checkbox_all_subscribers' type="checkbox" name="all_subscribers">
                    <label> Notifier tous les abonnés du domaine</label>
                </div>
            </div>
            <div id='field_select_subscribers' class="field">
                <select id='subscribers'  name="subscribers" multiple="" class="ui search fluid dropdown">
                    <option value="">Selectionner les abonnés à notifier</option>
                    {%if subscribers%}
                        {%for subscriber in subscribers %}
                            <option value="{{subscriber.id}}">{{subscriber.name}}({{subscriber.entreprise.name}})</option>
                        {%endfor%} 
                    {%endif%}
                </select>
            </div>

            <div id='field_common_notification' class="field">
                <select id='notificationTypes'  name="common_notification" class="ui search fluid dropdown">
                    <option value="">Selectionner un type de notification commun si nécessaire</option>                    
                    <option value="3">SMS et Email</option>
                    <option value="2">SMS seulement</option>
                    <option value="1">Email seulement</option>
                </select>
            </div>

            <div class="field">
                <div id="server_error_message_send_notification" class="ui negative message" style="display:none">
                    <i class="close icon"></i>
                    <div id="server_error_content_send_notification" class="header">Internal server error</div>
                </div>
                <div id="error_name_message_send_notification" class="ui error message" style="display: none">
                    <i class="close icon"></i>
                    <div id="error_name_header_send_notification" class="header"></div>
                    <ul id="error_name_list_send_notification" class="list">

                    </ul>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <div id="cancel_send_notification_procedureResult" class="ui black deny button">
            Annuler
        </div>
        <div id='submit_send_notification_procedureResult' class="ui primary icon button">
            <i class="send icon"></i>
            Envoyer
        </div>
    </div>
</div>

src/OGIVE/AlertBundle/Resources/views/send_sms/form_send_sms.html.twig
<div id="send_sms_subscriber" class="ui small modal">
    <i class="close icon"></i>
    <div class="header">
        Envoi d'un sms à << {{subscriber.name}}({{subscriber.phoneNumber}}) >>
    </div>
    <div class="content">
        {{ form_start(form, {'method': 'POST', 'action': path('send_sms_subscriber', {'id': subscriber.id}), 'attr': {'class': 'ui form', 'id': 'send_sms_subscriber_form'} }) }}
        <div class="field">
            {{ form_label(form.message,"Message") }}
            {{ form_widget(form.message,{'attr':{'id': 'abstract_sms', 'placeholder':"Le message à envoyer", 'data-validate': 'message'}})}}
            <label id="abstract_sms_length_notif">longueur du message : <span id="abstract_sms_count">{{form.message|length}}</span></label>
        </div>

        <div class="field">
            {#            {{form_rest(form)}}#}
            <div id="server_error_message_send_sms" class="ui negative message" style="display:none">
                <i class="close icon"></i>
                <div id="server_error_content_send_sms" class="header">Internal server error</div>
            </div>
            <div id="error_name_message_send_sms" class="ui error message" style="display: none">
                <i class="close icon"></i>
                <div id="error_name_header_send_sms" class="header"></div>
                <ul id="error_name_list_send_sms" class="list">

                </ul>
            </div>
        </div>
        {{form_widget(form._token)}}
        {#        {{ form_end(form) }}#}
        </form>
    </div>
    <div class="actions">
        <div id="cancel_send_sms_subscriber" class="ui black deny button">
            Annuler
        </div>
        <div id='submit_send_sms_subscriber' class="ui primary icon button">
            <i class="send icon"></i>
            Envoyer
        </div>
    </div>
</div>

src/OGIVE/AlertBundle/Resources/views/send_sms/form_send_special_follow_up.html.twig
<div id="send_special_follow_up" class="ui small modal">
    <i class="close icon"></i>
    <div class="header">
        Envoyer le suivi spécialisé : {{specialFollowUp.name}}
    </div>
    <div class="content">
        <form method = 'POST' action= '{{path('send_special_follow_up_post', {'id': specialFollowUp.id})}}' class = 'ui form' id ='send_special_follow_up_form' name='send_notification_specialFollowUp_form'>
            <div class="field">
                <label>Le message à envoyer</label>
                <textarea id='abstract_sms' name='abstract'>{{specialFollowUp.description}}</textarea>
                <label id="abstract_sms_length_notif">longueur du message : <span id="abstract_sms_count">{{specialFollowUp.description|length}}</span></label>
            </div>

            <div class="field" >
                <div class="ui checkbox">
                    <input id='checkbox_all_subscribers' type="checkbox" name="all_subscribers" >
                    <label> Envoyer à tous les abonnés</label>
                </div>
            </div>
            <div id='field_select_subscribers' class="field">
                <select id='subscribers'  name="subscribers" multiple="" class="ui search fluid dropdown">
                    <option value="">Selectionner les abonnés à notifier</option>
                    {%if subscribers%}
                        {%for subscriber in subscribers %}
                            <option value="{{subscriber.id}}">{{subscriber.name}}({{subscriber.entreprise.name}})</option>
                        {%endfor%} 
                    {%endif%}
                </select>
            </div>
                
            <div id='field_common_notification' class="field">
                <select id='notificationTypes'  name="common_notification" class="ui search fluid dropdown">
                    <option value="">Selectionner un type de notification commun si nécessaire</option>                    
                    <option value="3">SMS et Email</option>
                    <option value="2">SMS seulement</option>
                    <option value="1">Email seulement</option>
                </select>
            </div>

            <div class="field">
                <div id="server_error_message_send_notification" class="ui negative message" style="display:none">
                    <i class="close icon"></i>
                    <div id="server_error_content_send_notification" class="header">Internal server error</div>
                </div>
                <div id="error_name_message_send_notification" class="ui error message" style="display: none">
                    <i class="close icon"></i>
                    <div id="error_name_header_send_notification" class="header"></div>
                    <ul id="error_name_list_send_notification" class="list">

                    </ul>
                </div>
            </div>
        </form>
    </div>
    <div class="actions">
        <div id="cancel_send_special_follow_up" class="ui black deny button">
            Annuler
        </div>
        <div id='submit_send_special_follow_up' class="ui primary icon button">
            <i class="send icon"></i>
            Envoyer
        </div>
    </div>
</div>